---
title: "Modeling Counts"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Libraries


```{r libraries echo=FALSE}
library(tidyverse,warn.conflicts = FALSE)
library(rstan,warn.conflicts = FALSE)
library(devtools,warn.conflicts = FALSE)
library(lazyeval,warn.conflicts = FALSE)
library(cowplot,warn.conflicts = FALSE)
library(ggridges)
library(beepr)

normalit<-function(m){
    (m - min(m))/(max(m)-min(m))}
```


```{r data}

test_data <- read.csv('test_data.csv')[,2:5]
```

```{r}
data_O43707 <- filter(test_data,ProteinID=='O43707')
data_O43707 <- mutate(data_O43707,FractionID=substr(FractionID,7,8) %>% as.numeric)
sparkplot_O43707 <- sparkplot(test_data,'Peptide','FractionID','PeptideCount',groupid = 'ProteinID',group_name='O43707')
wide_O43707 <- spread(data_O43707,key=FractionID,value=PeptideCount)
ggdraw(sparkplot_O43707)

```

### Make data amenable for Stan
```{r}
fraction <- 1:max(data_O43707$FractionID)
peptides <- unique(data_O43707$Peptide)
counts <- wide_O43707[,3:50] %>% as.matrix() %>% apply(1,normalit) %>% t #normalize
```



### get argmax_f(count)
```{r}
index_max_count <- which(data_O43707$PeptideCount==max(data_O43707$PeptideCount))
argmax_f <- data_O43707[index_max_count,]$FractionID

```


### Feed data into Stan 
```{r}
stan_data <- list(
    F = max(data_O43707$FractionID),
    P = length(unique(data_O43707$Peptide)),
    counts = counts,
    peak = argmax_f
)
```


###Stan hierarchical Model
```{r pressure, echo=FALSE}
hmodel = "
data {
int F; // number of fractions
int P; // number of peptides
int peak; //fraction with a peak
matrix[P,F] counts;
}

parameters {
real<lower=0> mu_p;
real<lower=0> sd_p;
real sigma_in_u;
real<lower=0> sigma_out;

vector[P] mu;
}

transformed parameters{
real<lower=0> sigma_in;
sigma_in = exp(sigma_in_u);


}


model {

// prior
mu_p ~ normal(peak,3);
sd_p ~ gamma(2,0.5);
mu ~ normal(mu_p,sd_p);
sigma_in_u ~ normal(0.7,1);
sigma_out ~ gamma(2,0.5);



// likelihood
for(p in 1:P){
    for(f in 1:F){
        counts[p,f] ~ normal(exp(pow(f-mu[p],2)/(-2*pow(sigma_in,2))),sigma_out);
    }
}
}

generated quantities {

matrix[P,F] counts_hat;

for(p in 1:P){
    for(f in 1:F){
        counts_hat[p,f] = normal_rng(exp(pow(f-mu[p],2)/(-2*pow(sigma_in,2))),sigma_out);
    }
}


}
"
```

###Run Stan Model
```{r}
count_fit <- stan(
    model_code = hmodel,
    data = stan_data,
    chains = 4,
    warmup = 1000,
    iter = 2000,
    cores = 4,
    refresh = 1000
)

as.data.frame(summary(count_fit)$summary)

beep(8)
```

```{r}
as.data.frame(summary(count_fit)$summary)

hm_extract <- extract(count_fit)
```

```{r, fig.width=6,fig.height=4}
posteriors <- data.frame(hm_extract$mu_p,hm_extract$sd_p,hm_extract$sigma_in_u,hm_extract$sigma_in,hm_extract$sigma_out,hm_extract$mu) %>% setNames(c('mu_p','sd_p','sigma_in_u','sigma_in','sigma_out','mu'))
ggplot(gather(posteriors,key='parameter'),aes(y=parameter,x=value,fill=parameter,color=parameter)) + geom_density_ridges(scale=3,alpha=0.5) + scale_x_continuous(limits=c(min(posteriors),max(posteriors)))
```





```{r, fig.width=6}
#as.data.frame(hm_extract$counts_hat[1,1:52,1:48]) %>% View

posterior_means <- rstan::get_posterior_mean(count_fit)
rownames(posterior_means)

counts_hat <- posterior_means[58:2553,5]
counts_prediction_means <- matrix(counts_hat,nrow=48,ncol=52) %>% t %>% apply(1,normalit) %>% t

tidy_prediction_means <- as.data.frame(counts_prediction_means) %>% mutate(peptide=1:52) %>% gather(key='fraction',value='count',-peptide,factor_key = TRUE) %>% mutate(fraction=substr(fraction,2,4) %>% as.numeric())

#plot(counts_prediction_means[3,],type='l')

ggplot(data=filter(tidy_prediction_means,peptide==2),aes(x=fraction,y=count)) + geom_line()

ggplot(data=tidy_prediction_means,aes(group=peptide,y=peptide,x=fraction,height=count)) + geom_ridgeline(scale=8,fill='grey',alpha=0.2,color=1)

```







